name: Build and Deploy delete-product to EC2 from QA

on:
  push:
    branches:
      - qa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: qa

    steps:
      # Checkout the code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build image with 'qa' tag
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/delete-product:${{ env.IMAGE_TAG }} .

      # Push image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/delete-product:${{ env.IMAGE_TAG }}

      # Setup SSH key
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      # Deploy the container to EC2 using the image from Docker Hub
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e

            echo "📦 Deploying delete-product using Docker Hub image (qa)..."

            # Install Docker if it's not installed
            if ! command -v docker &> /dev/null; then
              echo "🛠 Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            else
              echo "✅ Docker is already installed."
            fi

            # Stop and remove existing container if any
            sudo docker rm -f delete-product || true

            # Pull the image from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/delete-product:${{ env.IMAGE_TAG }}

            # Run the container
            sudo docker run -d --name delete-product \
              -p 4004:4004 \
              --restart=always \
              -e MONGODB_URI=mongodb://52.21.72.12:27017 \
              -e DB_NAME=toyshop_db \
              -e PORT=4004 \
              ${{ secrets.DOCKER_USERNAME }}/delete-product:${{ env.IMAGE_TAG }}

            echo "✅ delete-product deployed successfully (qa)"
            sudo docker ps -a
          EOF